Logging to outputs/train_logs/finetune_20260424_120205.log
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
INFO 2026-04-24 12:02:38 ot_train.py:197 {'batch_size': 128,
 'checkpoint_path': None,
 'cudnn_deterministic': False,
 'dataset': {'episodes': None,
             'image_transforms': {'enable': False,
                                  'max_num_transforms': 3,
                                  'random_order': False,
                                  'tfs': {'affine': {'kwargs': {'degrees': [-5.0,
                                                                            5.0],
                                                                'translate': [0.05,
                                                                              0.05]},
                                                     'type': 'RandomAffine',
                                                     'weight': 1.0},
                                          'brightness': {'kwargs': {'brightness': [0.8,
                                                                                   1.2]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'contrast': {'kwargs': {'contrast': [0.8,
                                                                               1.2]},
                                                       'type': 'ColorJitter',
                                                       'weight': 1.0},
                                          'hue': {'kwargs': {'hue': [-0.05,
                                                                     0.05]},
                                                  'type': 'ColorJitter',
                                                  'weight': 1.0},
                                          'saturation': {'kwargs': {'saturation': [0.5,
                                                                                   1.5]},
                                                         'type': 'ColorJitter',
                                                         'weight': 1.0},
                                          'sharpness': {'kwargs': {'sharpness': [0.5,
                                                                                 1.5]},
                                                        'type': 'SharpnessJitter',
                                                        'weight': 1.0}}},
             'repo_id': 'local/libero_lerobot_v3_lerobotkeys',
             'revision': None,
             'root': '/nfs/bigflow/add_disk0/jongwoopark/libero_lerobot_v3_lerobotkeys',
             'streaming': False,
             'use_imagenet_stats': True,
             'video_backend': 'torchcodec'},
 'env': {'camera_name': 'agentview_image,robot0_eye_in_hand_image',
         'camera_name_mapping': None,
         'control_mode': 'relative',
         'disable_env_checker': True,
         'episode_length': None,
         'features': {'action': {'shape': [7],
                                 'type': <FeatureType.ACTION: 'ACTION'>},
                      'pixels/agentview_image': {'shape': [360, 360, 3],
                                                 'type': <FeatureType.VISUAL: 'VISUAL'>},
                      'pixels/robot0_eye_in_hand_image': {'shape': [360,
                                                                    360,
                                                                    3],
                                                          'type': <FeatureType.VISUAL: 'VISUAL'>},
                      'robot_state/eef/mat': {'shape': [3, 3],
                                              'type': <FeatureType.STATE: 'STATE'>},
                      'robot_state/eef/pos': {'shape': [3],
                                              'type': <FeatureType.STATE: 'STATE'>},
                      'robot_state/eef/quat': {'shape': [4],
                                               'type': <FeatureType.STATE: 'STATE'>},
                      'robot_state/gripper/qpos': {'shape': [2],
                                                   'type': <FeatureType.STATE: 'STATE'>},
                      'robot_state/gripper/qvel': {'shape': [2],
                                                   'type': <FeatureType.STATE: 'STATE'>},
                      'robot_state/joints/pos': {'shape': [7],
                                                 'type': <FeatureType.STATE: 'STATE'>},
                      'robot_state/joints/vel': {'shape': [7],
                                                 'type': <FeatureType.STATE: 'STATE'>}},
         'features_map': {'action': 'action',
                          'pixels/agentview_image': 'observation.images.image',
                          'pixels/robot0_eye_in_hand_image': 'observation.images.image2',
                          'robot_state/eef/mat': 'observation.state.eef_mat',
                          'robot_state/eef/pos': 'observation.state.eef_pos',
                          'robot_state/eef/quat': 'observation.state.eef_quat',
                          'robot_state/gripper/qpos': 'observation.state.gripper_qpos',
                          'robot_state/gripper/qvel': 'observation.state.gripper_qvel',
                          'robot_state/joints/pos': 'observation.state.joint_pos',
                          'robot_state/joints/vel': 'observation.state.joint_vel'},
         'fps': 30,
         'init_states': True,
         'max_parallel_tasks': 1,
         'obs_type': 'pixels_agent_pos',
         'observation_height': 360,
         'observation_width': 360,
         'render_mode': 'rgb_array',
         'task': 'libero_spatial,libero_object,libero_goal,libero_10',
         'task_ids': None,
         'type': 'libero'},
 'eval': {'batch_size': 1, 'n_episodes': 1, 'use_async_envs': False},
 'eval_freq': 1000000,
 'job_name': 'smolvla_libero_multitask_20260424_120205',
 'log_freq': 200,
 'num_workers': 4,
 'optimizer': {'betas': [0.9, 0.95],
               'eps': 1e-08,
               'grad_clip_norm': 10,
               'lr': 0.0001,
               'type': 'adamw',
               'weight_decay': 1e-10},
 'output_dir': 'outputs/train/smolvla_libero_multitask_20260424_120205',
 'peft': None,
 'policy': {'adapt_to_pi_aloha': False,
            'add_image_special_tokens': False,
            'attention_mode': 'cross_attn',
            'chunk_size': 50,
            'compile_mode': 'max-autotune',
            'compile_model': False,
            'device': 'cuda',
            'empty_cameras': 0,
            'expert_width_multiplier': 0.75,
            'freeze_vision_encoder': True,
            'input_features': {},
            'license': None,
            'load_vlm_weights': True,
            'max_action_dim': 32,
            'max_period': 4.0,
            'max_state_dim': 32,
            'min_period': 0.004,
            'n_action_steps': 1,
            'n_obs_steps': 1,
            'normalization_mapping': {'ACTION': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'STATE': <NormalizationMode.MEAN_STD: 'MEAN_STD'>,
                                      'VISUAL': <NormalizationMode.IDENTITY: 'IDENTITY'>},
            'num_expert_layers': -1,
            'num_steps': 10,
            'num_vlm_layers': 16,
            'optimizer_betas': [0.9, 0.95],
            'optimizer_eps': 1e-08,
            'optimizer_grad_clip_norm': 10,
            'optimizer_lr': 0.0001,
            'optimizer_weight_decay': 1e-10,
            'output_features': {},
            'pad_language_to': 'longest',
            'prefix_length': -1,
            'pretrained_path': None,
            'private': None,
            'push_to_hub': False,
            'repo_id': None,
            'resize_imgs_with_padding': [512, 512],
            'rtc_config': None,
            'scheduler_decay_lr': 2.5e-06,
            'scheduler_decay_steps': 5000,
            'scheduler_warmup_steps': 50,
            'self_attn_every_n_layers': 2,
            'tags': None,
            'tokenizer_max_length': 48,
            'train_expert_only': True,
            'train_state_proj': True,
            'type': 'smolvla',
            'use_amp': False,
            'use_cache': True,
            'use_delta_joint_actions_aloha': False,
            'use_peft': False,
            'vlm_model_name': 'HuggingFaceTB/SmolVLM2-500M-Video-Instruct'},
 'rabc_epsilon': 1e-06,
 'rabc_head_mode': 'sparse',
 'rabc_kappa': 0.01,
 'rabc_progress_path': None,
 'rename_map': {},
 'resume': False,
 'save_checkpoint': True,
 'save_freq': 20000,
 'scheduler': {'decay_lr': 2.5e-06,
               'num_decay_steps': 5000,
               'num_warmup_steps': 50,
               'peak_lr': 0.0001,
               'type': 'cosine_decay_with_warmup'},
 'seed': 1000,
 'steps': 5000,
 'tolerance_s': 0.0001,
 'use_policy_training_preset': True,
 'use_rabc': False,
 'wandb': {'add_tags': True,
           'disable_artifact': False,
           'enable': False,
           'entity': None,
           'mode': None,
           'notes': None,
           'project': 'lerobot',
           'run_id': None}}