#!/usr/bin/env bash
set -euo pipefail

# BigBrain stage-0 LP-MT HiVA coefficient finetune matching the prior
# BigCornea K=4/F=15 coeff-pool run, with BigBrain b256/GPU, S=0.25, 10k steps.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

RUN_STAMP="${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}"
LOG_DIR="${REPO_ROOT}/outputs/train_logs"
mkdir -p "${LOG_DIR}"

SIDECAR_ROOT="${SIDECAR_ROOT:-/nfs/bigbrain/add_disk0/jongwoopark}"
DATA_ROOT="${DATA_ROOT:-${SIDECAR_ROOT}/libero_lerobot_v3_lerobotkeys}"
TOTAL_STEPS="${TOTAL_STEPS:-10000}"
SAVE_STEPS="${SAVE_STEPS:-[6000,6250,7000,7500,8750,10000]}"
GPU_IDS="${GPU_IDS:-8,9}"
NUM_PROCESSES="${NUM_PROCESSES:-2}"
BATCH_PER_GPU="${BATCH_PER_GPU:-256}"
BATCH_SIZE="${BATCH_SIZE:-${BATCH_PER_GPU}}"
S="${S:-0.25}"
HIVA_K="${HIVA_K:-4}"
HIVA_FIT_HORIZON="${HIVA_FIT_HORIZON:-15}"
HIVA_DEGREE="${HIVA_DEGREE:-3}"

S_TAG="${S//./p}"
RUN_NAME="${RUN_NAME:-smolvla_hiva_coeff_lpmt_stage0_v5_d4_6_10_coeffpool_full_ce_mean_k${HIVA_K}_f${HIVA_FIT_HORIZON}_bigbrain_b${BATCH_PER_GPU}_g${NUM_PROCESSES}_s${S_TAG}_steps${TOTAL_STEPS}_${RUN_STAMP}}"
QUEUE_LOG="${QUEUE_LOG:-${LOG_DIR}/hiva_coeff_lpmt_stage0_v5_k${HIVA_K}_f${HIVA_FIT_HORIZON}_s${S_TAG}_b${BATCH_PER_GPU}_g${NUM_PROCESSES}_gpu8_9_steps${TOTAL_STEPS}_bigbrain_${RUN_STAMP}.log}"

echo "Launching K=${HIVA_K}, F=${HIVA_FIT_HORIZON} LP-MT HiVA on BigBrain"
echo "RUN_NAME=${RUN_NAME}"
echo "GPU_IDS=${GPU_IDS}"
echo "BATCH_PER_GPU=${BATCH_PER_GPU}"
echo "S=${S}"
echo "TOTAL_STEPS=${TOTAL_STEPS}"
echo "SAVE_STEPS=${SAVE_STEPS}"

RUN_STAMP="${RUN_STAMP}" \
RUN_NAME="${RUN_NAME}" \
QUEUE_LOG="${QUEUE_LOG}" \
GPU_IDS="${GPU_IDS}" \
NUM_PROCESSES="${NUM_PROCESSES}" \
MAIN_PROCESS_PORT="${MAIN_PROCESS_PORT:-0}" \
BATCH_PER_GPU="${BATCH_PER_GPU}" \
BATCH_SIZE="${BATCH_SIZE}" \
S="${S}" \
TOTAL_STEPS="${TOTAL_STEPS}" \
SAVE_STEPS="${SAVE_STEPS}" \
SCHEDULER_WARMUP_STEPS="${SCHEDULER_WARMUP_STEPS:-300}" \
SCHEDULER_DECAY_STEPS="${SCHEDULER_DECAY_STEPS:-${TOTAL_STEPS}}" \
SIDECAR_ROOT="${SIDECAR_ROOT}" \
DATA_ROOT="${DATA_ROOT}" \
DATA_REPO_ID="${DATA_REPO_ID:-local/libero_lerobot_v3_lerobotkeys}" \
SIDECAR="${SIDECAR:-${SIDECAR_ROOT}/libero_hiva_coeff_sidecar_v5_d4_6_10_wide_commit6_k${HIVA_K}_f${HIVA_FIT_HORIZON}_canonical_lp_mt.parquet}" \
SIDECAR_SUMMARY="${SIDECAR_SUMMARY:-${SIDECAR_ROOT}/libero_hiva_coeff_sidecar_v5_d4_6_10_wide_commit6_k${HIVA_K}_f${HIVA_FIT_HORIZON}_canonical_lp_mt.summary.json}" \
HIVA_DURATION_CLASSES="${HIVA_DURATION_CLASSES:-[4,6,10]}" \
HIVA_DMAX="${HIVA_DMAX:-10}" \
HIVA_FIT_HORIZON="${HIVA_FIT_HORIZON}" \
HIVA_K="${HIVA_K}" \
HIVA_DEGREE="${HIVA_DEGREE}" \
HIVA_DEGREE_TR="${HIVA_DEGREE_TR:-${HIVA_DEGREE}}" \
HIVA_DEGREE_ROT="${HIVA_DEGREE_ROT:-${HIVA_DEGREE}}" \
HIVA_DEGREE_GRIP="${HIVA_DEGREE_GRIP:-${HIVA_DEGREE}}" \
HIVA_BASIS_MODE="${HIVA_BASIS_MODE:-canonical_lp_mt}" \
HIVA_DURATION_LOSS="${HIVA_DURATION_LOSS:-ce_mean}" \
HIVA_SUFFIX_ATTENTION="${HIVA_SUFFIX_ATTENTION:-full}" \
HIVA_DURATION_READOUT="${HIVA_DURATION_READOUT:-coeff_modality_pool}" \
HIVA_DURATION_HEAD_TYPE="${HIVA_DURATION_HEAD_TYPE:-residual_ffn}" \
HIVA_DURATION_PREDICTION_TYPE="${HIVA_DURATION_PREDICTION_TYPE:-categorical}" \
HIVA_TR_LOSS_WEIGHT="${HIVA_TR_LOSS_WEIGHT:-1.0}" \
HIVA_ROT_LOSS_WEIGHT="${HIVA_ROT_LOSS_WEIGHT:-1.0}" \
HIVA_GRIP_LOSS_WEIGHT="${HIVA_GRIP_LOSS_WEIGHT:-1.0}" \
HIVA_DURATION_NOISY_LOSS_WEIGHT="${HIVA_DURATION_NOISY_LOSS_WEIGHT:-1.0}" \
HIVA_DURATION_CLEAN_LOSS_WEIGHT="${HIVA_DURATION_CLEAN_LOSS_WEIGHT:-0.0}" \
HIVA_DURATION_FM_LOSS_WEIGHT="${HIVA_DURATION_FM_LOSS_WEIGHT:-1.0}" \
HIVA_DURATION_NOISY_SIGMA="${HIVA_DURATION_NOISY_SIGMA:-0.25}" \
HIVA_DURATION_CONT_NORM="${HIVA_DURATION_CONT_NORM:-bounded}" \
HIVA_DECODED_ACTION_LOSS_WEIGHT="${HIVA_DECODED_ACTION_LOSS_WEIGHT:-0.0}" \
HIVA_DECODED_TR_LOSS_WEIGHT="${HIVA_DECODED_TR_LOSS_WEIGHT:-1.0}" \
HIVA_DECODED_ROT_LOSS_WEIGHT="${HIVA_DECODED_ROT_LOSS_WEIGHT:-1.0}" \
HIVA_DECODED_GRIP_LOSS_WEIGHT="${HIVA_DECODED_GRIP_LOSS_WEIGHT:-1.0}" \
HIVA_DECODED_PREFIX_WEIGHT="${HIVA_DECODED_PREFIX_WEIGHT:-1.0}" \
HIVA_DECODED_POST_DURATION_EXEC_WEIGHT="${HIVA_DECODED_POST_DURATION_EXEC_WEIGHT:-0.5}" \
HIVA_DECODED_PREVIEW_WEIGHT="${HIVA_DECODED_PREVIEW_WEIGHT:-0.1}" \
HIVA_DECODED_TERMINAL_WEIGHT="${HIVA_DECODED_TERMINAL_WEIGHT:-0.0}" \
HIVA_DECODED_LOSS_BETA="${HIVA_DECODED_LOSS_BETA:-0.1}" \
HIVA_RESIDUAL_ENABLED="${HIVA_RESIDUAL_ENABLED:-false}" \
HIVA_RESIDUAL_HORIZON="${HIVA_RESIDUAL_HORIZON:-${HIVA_FIT_HORIZON}}" \
HIVA_RESIDUAL_FFN_HIDDEN_MULT="${HIVA_RESIDUAL_FFN_HIDDEN_MULT:-4.0}" \
HIVA_RESIDUAL_TOKEN_TIME_HIDDEN_MULT="${HIVA_RESIDUAL_TOKEN_TIME_HIDDEN_MULT:-2.0}" \
HIVA_RESIDUAL_ALPHA_INIT="${HIVA_RESIDUAL_ALPHA_INIT:-0.1}" \
HIVA_RESIDUAL_ZERO_INIT="${HIVA_RESIDUAL_ZERO_INIT:-true}" \
POLICY_CHUNK_SIZE="${POLICY_CHUNK_SIZE:-15}" \
POLICY_N_ACTION_STEPS="${POLICY_N_ACTION_STEPS:-10}" \
WANDB_ENABLE="${WANDB_ENABLE:-true}" \
WANDB_PROJECT="${WANDB_PROJECT:-lerobot}" \
WANDB_MODE="${WANDB_MODE:-online}" \
WANDB_DISABLE_ARTIFACT="${WANDB_DISABLE_ARTIFACT:-true}" \
WANDB_NOTES="${WANDB_NOTES:-K=4 F=15 LP-MT HiVA stage0 finetune matching prior BigCornea run; S=0.25; batch_per_gpu=256; GPUs=8,9; steps=10000; save_steps=${SAVE_STEPS}}" \
DRY_RUN="${DRY_RUN:-0}" \
bash "${SCRIPT_DIR}/run_hiva_coeff_lpmt_stage0_p5_s0p5_5000_bigbrain.sh" --total-steps "${TOTAL_STEPS}"

