#!/usr/bin/env bash
set -euo pipefail

# Canonical long-preview max-target (LP-MT) HiVA coefficient SmolVLA finetuning on bigflow.
#
# LP-MT decodes a preview chunk of HIVA_FIT_HORIZON actions with one canonical basis, while the
# duration head chooses only an executable prefix in HIVA_DURATION_CLASSES. Defaults use {2,15},
# executable Dmax=15, preview/fit horizon=20, K=10, residual FFN duration head, CE mean duration
# loss, and duration-reads-coefficients suffix attention.
#
# Example:
#   GPU_IDS=4,5,6,7 NUM_GPUS=4 BATCH_PER_GPU=160 S=2 WANDB_ENABLE=true \
#   bash server_scripts/bigflow/finetune_bigflow_ckpt_20k_hiva_coeff_lp_mt.sh
#
# Smoke:
#   GPU_IDS=0 NUM_GPUS=1 NUM_PROCESSES=1 BATCH_PER_GPU=2 STEPS=2 SAVE_FREQ=1 \
#   WANDB_ENABLE=false \
#   bash server_scripts/bigflow/finetune_bigflow_ckpt_20k_hiva_coeff_lp_mt.sh

if [[ "${HIVA_SCRIPT_SNAPSHOT:-0}" != "1" ]]; then
  SNAPSHOT_ROOT="${HIVA_SCRIPT_SNAPSHOT_ROOT:-/tmp/jongwoopark_hiva_script_snapshots}"
  mkdir -p "${SNAPSHOT_ROOT}"
  SNAPSHOT_PATH="${SNAPSHOT_ROOT}/$(basename "$0").$USER.$(date +%Y%m%d_%H%M%S_%N).$$.sh"
  cp "$0" "${SNAPSHOT_PATH}"
  chmod +x "${SNAPSHOT_PATH}"
  export HIVA_SCRIPT_SNAPSHOT=1
  export HIVA_ORIGINAL_SCRIPT_PATH="$(readlink -f "$0")"
  exec bash "${SNAPSHOT_PATH}" "$@"
fi

SCRIPT_PATH="${HIVA_ORIGINAL_SCRIPT_PATH:-$(readlink -f "$0")}"
SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"

HIVA_DURATION_CLASSES="${HIVA_DURATION_CLASSES:-[2,15]}"
HIVA_DMAX="${HIVA_DMAX:-15}"
HIVA_FIT_HORIZON="${HIVA_FIT_HORIZON:-20}"
HIVA_K="${HIVA_K:-10}"
HIVA_DEGREE="${HIVA_DEGREE:-3}"
HIVA_DEGREE_TR="${HIVA_DEGREE_TR:-}"
HIVA_DEGREE_ROT="${HIVA_DEGREE_ROT:-}"
HIVA_DEGREE_GRIP="${HIVA_DEGREE_GRIP:-}"
HIVA_BASIS_MODE="${HIVA_BASIS_MODE:-canonical_lp_mt}"
HIVA_DURATION_LOSS="${HIVA_DURATION_LOSS:-ce_mean}"
HIVA_SUFFIX_ATTENTION="${HIVA_SUFFIX_ATTENTION:-duration_reads_coeffs}"
HIVA_DURATION_HEAD_TYPE="${HIVA_DURATION_HEAD_TYPE:-residual_ffn}"
HIVA_DURATION_NOISY_LOSS_WEIGHT="${HIVA_DURATION_NOISY_LOSS_WEIGHT:-1.0}"
HIVA_DURATION_CLEAN_LOSS_WEIGHT="${HIVA_DURATION_CLEAN_LOSS_WEIGHT:-0.0}"
HIVA_DURATION_NOISY_SIGMA="${HIVA_DURATION_NOISY_SIGMA:-0.25}"
HIVA_DURATION_PREDICTION_TYPE="${HIVA_DURATION_PREDICTION_TYPE:-categorical}"
HIVA_DURATION_READOUT="${HIVA_DURATION_READOUT:-token}"
HIVA_DURATION_FM_LOSS_WEIGHT="${HIVA_DURATION_FM_LOSS_WEIGHT:-1.0}"
HIVA_DURATION_CONT_NORM="${HIVA_DURATION_CONT_NORM:-bounded}"
HIVA_DURATION_MEAN="${HIVA_DURATION_MEAN:-}"
HIVA_DURATION_STD="${HIVA_DURATION_STD:-}"
HIVA_DECODED_ACTION_LOSS_WEIGHT="${HIVA_DECODED_ACTION_LOSS_WEIGHT:-0.0}"
HIVA_DECODED_TR_LOSS_WEIGHT="${HIVA_DECODED_TR_LOSS_WEIGHT:-1.0}"
HIVA_DECODED_ROT_LOSS_WEIGHT="${HIVA_DECODED_ROT_LOSS_WEIGHT:-1.0}"
HIVA_DECODED_GRIP_LOSS_WEIGHT="${HIVA_DECODED_GRIP_LOSS_WEIGHT:-1.0}"
HIVA_DECODED_PREFIX_WEIGHT="${HIVA_DECODED_PREFIX_WEIGHT:-1.0}"
HIVA_DECODED_POST_DURATION_EXEC_WEIGHT="${HIVA_DECODED_POST_DURATION_EXEC_WEIGHT:-0.5}"
HIVA_DECODED_PREVIEW_WEIGHT="${HIVA_DECODED_PREVIEW_WEIGHT:-0.1}"
HIVA_DECODED_TERMINAL_WEIGHT="${HIVA_DECODED_TERMINAL_WEIGHT:-0.0}"
HIVA_DECODED_LOSS_BETA="${HIVA_DECODED_LOSS_BETA:-0.1}"
HIVA_RESIDUAL_ENABLED="${HIVA_RESIDUAL_ENABLED:-false}"
HIVA_RESIDUAL_HORIZON="${HIVA_RESIDUAL_HORIZON:-${HIVA_FIT_HORIZON}}"
HIVA_RESIDUAL_FFN_HIDDEN_MULT="${HIVA_RESIDUAL_FFN_HIDDEN_MULT:-4.0}"
HIVA_RESIDUAL_TOKEN_TIME_HIDDEN_MULT="${HIVA_RESIDUAL_TOKEN_TIME_HIDDEN_MULT:-2.0}"
HIVA_RESIDUAL_ALPHA_INIT="${HIVA_RESIDUAL_ALPHA_INIT:-0.1}"
HIVA_RESIDUAL_ZERO_INIT="${HIVA_RESIDUAL_ZERO_INIT:-true}"
HIVA_RESIDUAL_SCALE_TR="${HIVA_RESIDUAL_SCALE_TR:-}"
HIVA_RESIDUAL_SCALE_ROT="${HIVA_RESIDUAL_SCALE_ROT:-}"
HIVA_RESIDUAL_SCALE_GRIP="${HIVA_RESIDUAL_SCALE_GRIP:-}"
SIDECAR="${SIDECAR:-/nfs/bigflow/add_disk0/jongwoopark/libero_hiva_coeff_sidecar_d2_15_w1_10_w3_0_k${HIVA_K}_f${HIVA_FIT_HORIZON}_canonical_lp_mt.parquet}"
SIDECAR_SUMMARY="${SIDECAR_SUMMARY:-/nfs/bigflow/add_disk0/jongwoopark/libero_hiva_coeff_sidecar_d2_15_w1_10_w3_0_k${HIVA_K}_f${HIVA_FIT_HORIZON}_canonical_lp_mt.summary.json}"

if [[ -z "${RUN_NAME:-}" ]]; then
  DURATION_RUN_SUFFIX="${HIVA_DURATION_LOSS}"
  if [[ "${HIVA_DURATION_PREDICTION_TYPE}" != "categorical" ]]; then
    DURATION_RUN_SUFFIX="${HIVA_DURATION_PREDICTION_TYPE}_${HIVA_DURATION_CONT_NORM}"
  elif [[ "${HIVA_DURATION_READOUT}" != "token" ]]; then
    DURATION_RUN_SUFFIX="${HIVA_DURATION_READOUT}_${DURATION_RUN_SUFFIX}"
  fi
  RUN_NAME="smolvla_hiva_coeff_lpmt_${HIVA_DURATION_HEAD_TYPE}_${HIVA_SUFFIX_ATTENTION}_${DURATION_RUN_SUFFIX}_d2_15_k${HIVA_K}_f${HIVA_FIT_HORIZON}_bigflow_b${BATCH_PER_GPU:-160}_s${S:-2}_$(date +%Y%m%d_%H%M%S)"
fi

export HIVA_DURATION_CLASSES
export HIVA_DMAX
export HIVA_FIT_HORIZON
export HIVA_K
export HIVA_DEGREE
export HIVA_DEGREE_TR
export HIVA_DEGREE_ROT
export HIVA_DEGREE_GRIP
export HIVA_BASIS_MODE
export HIVA_DURATION_LOSS
export HIVA_SUFFIX_ATTENTION
export HIVA_DURATION_HEAD_TYPE
export HIVA_DURATION_NOISY_LOSS_WEIGHT
export HIVA_DURATION_CLEAN_LOSS_WEIGHT
export HIVA_DURATION_NOISY_SIGMA
export HIVA_DURATION_PREDICTION_TYPE
export HIVA_DURATION_READOUT
export HIVA_DURATION_FM_LOSS_WEIGHT
export HIVA_DURATION_CONT_NORM
export HIVA_DURATION_MEAN
export HIVA_DURATION_STD
export HIVA_DECODED_ACTION_LOSS_WEIGHT
export HIVA_DECODED_TR_LOSS_WEIGHT
export HIVA_DECODED_ROT_LOSS_WEIGHT
export HIVA_DECODED_GRIP_LOSS_WEIGHT
export HIVA_DECODED_PREFIX_WEIGHT
export HIVA_DECODED_POST_DURATION_EXEC_WEIGHT
export HIVA_DECODED_PREVIEW_WEIGHT
export HIVA_DECODED_TERMINAL_WEIGHT
export HIVA_DECODED_LOSS_BETA
export HIVA_RESIDUAL_ENABLED
export HIVA_RESIDUAL_HORIZON
export HIVA_RESIDUAL_FFN_HIDDEN_MULT
export HIVA_RESIDUAL_TOKEN_TIME_HIDDEN_MULT
export HIVA_RESIDUAL_ALPHA_INIT
export HIVA_RESIDUAL_ZERO_INIT
export HIVA_RESIDUAL_SCALE_TR
export HIVA_RESIDUAL_SCALE_ROT
export HIVA_RESIDUAL_SCALE_GRIP
export POLICY_CHUNK_SIZE="${POLICY_CHUNK_SIZE:-${HIVA_FIT_HORIZON}}"
export POLICY_N_ACTION_STEPS="${POLICY_N_ACTION_STEPS:-${HIVA_DMAX}}"
export SIDECAR
export SIDECAR_SUMMARY
export RUN_NAME

exec bash "${SCRIPT_DIR}/finetune_bigflow_ckpt_20k_hiva_coeff_hp.sh"
